### ISSUE TITLE
Functions in the demo files don't match the functions in Phenor

### ISSUE THREAD

**Issue by catubela** [bluegreen-labs/phenor#31]
Perhaps I have missed something important here (I'm relatively new to R) but the functions used in the demo_data.R file like 'format_pep725' are not listed within the package? How many of the functions have changed from the version on Phenor used in your paper cited?
Many thanks.

**Comment by khufkens** [comment]
All of them, the package was refactored for consistency and ROpenSci compliance.

If you want the old setup use release version 1, as mentioned in the installation instructions.

https://bluegreen-labs.github.io/phenor/#installation

https://github.com/bluegreen-labs/phenor/releases/tag/v1.0

All functions were mostly just renamed so you should be able to go through the help files / index to figure out what you need (is equivalent to any old demo code).

https://bluegreen-labs.github.io/phenor/reference/index.html

**Comment by catubela** [comment]
Thank you. I don't know how I missed the Version1 comment on github.
