### ISSUE TITLE
The problem in UN model parameter ranges

### ISSUE THREAD

**Issue by MrJGao** [bluegreen-labs/phenor#35]
So, I was using `phenor` package to conduct some analysis. I found that the UN model could generate incorrect chilling-forcing relationships due to the ranges of `w` and `k`.  Specifically, the threshold of thermal forcing is modeled as $F_{crit} = w * exp(k * C_tot)$, according to Cannel & Smith 1983 and Chuine et al 2000, the larger `C_tot` is, the smaller $F_{crit}$ should be. So, one of `w` and `k` should be negative and the other one positive. Currently, the lower and upper bounds sent to the optimization methods for `w` is [-10, 10] and for `k` is [0, 100]. When fitting the UN model, I found that the estimated `w` and `k` are all positive, which means the chilling-forcing relationship is positive, which is incorrect. 

To fix the problem, after some tests, I found that bounds of `w` and `k` could be set to [0, 10] and [-100, 0], respectively.

Not sure if the problem exists for other datasets, just want to raise some attention here. If I'm correct, the [parameter_ranges.csv](https://github.com/bluegreen-labs/phenor/blob/master/inst/extdata/parameter_ranges.csv) file should be changed accordingly.

**Comment by MrJGao** [comment]
Sure! Here is a small example:

```
library(phenor)

data("phenocam_EN")
test_data <- phenocam_EN

set.seed(1234)

# Use orignal bounds
optim.par <- pr_fit_parameters(
    par = c(100, 0.5, 3, -4, -0.4, 10, 9, 0, 7),
    data = test_data,
    cost = rmse,
    model = "UN",
    method = "GenSA",
    lower = c(1, 0, 0.1, -20, -20, -5, -10, 0, 0),
    upper = c(365, 10, 10, 0.1, 0.1, 20, 10, 100, 350),
    control = NULL
)

# You'd find these parameters are all positive
w <- optim.par$par[7] # F* parameter w
k <- optim.par$par[8] # F* parameter k
ctot <- seq(1, 10, length = 100) # a fake C_tot
forc <- w * exp(k * ctot)

par(mfrow = c(1, 2))
# The estimated chilling-forcing relationship is positive, which is incorrect
plot(ctot, forc, type = "l", xlab = "Chilling", ylab = "Forcing", main = "Before")

# Fix the bounds
optim.par2 <- pr_fit_parameters(
    par = c(100, 0.5, 3, -4, -0.4, 10, 9, 0, 7),
    data = test_data,
    cost = rmse,
    model = "UN",
    method = "GenSA",
    lower = c(1, 0, 0.1, -20, -20, -5, 0, -100, 0),
    upper = c(365, 10, 10, 0.1, 0.1, 20, 10, 0, 350),
    control = list(maxit = 3000)
)

# Now you'll find `w` is positive but `k` is negative
w <- optim.par2$par[7] # F* parameter w
k <- optim.par2$par[8] # F* parameter k
forc <- w * exp(k * ctot)
# Now, the relationship is correct.
plot(ctot, forc, type = "l", xlab = "Chilling", ylab = "Forcing", main = "After")
```

Running the above code would plot a figure like this:
![image](https://user-images.githubusercontent.com/7261090/167697919-ba1464c0-9aa9-49de-9641-366fa2a9da95.png)


Btw, the issue was noticed by Dr. Josh Gray, I only tracked it down to the source code.

**Comment by khufkens** [comment]
Thanks to both of you.

Will fix.

Say hi to Josh !

**Comment by khufkens** [comment]
Fixed and included in new minor release

https://github.com/bluegreen-labs/phenor/releases/tag/v1.3.1
