### ISSUE TITLE
AT model bug

### ISSUE THREAD

**Issue by MrJGao** [bluegreen-labs/phenor#37]
In the file `phenology_models.R`, lines 32-34:

```{r}
# chilling
Rc <- data$Ti - T_base
Rc[Rc < 0] <- 1
Rc[Rc >= 0] <- 0
```

here the code computes chill days, but the calculation is wrong. 

The first line `Rc <- data$Ti - T_base` compares the daily mean temperature to the base temperature, then `Rc[Rc < 0] <- 1` assigns 0 to days when the daily mean temperature is higher than the base temperature. Now, the values in the `Rc` array are either 0 or a positive value. However, `Rc[Rc >= 0] <- 0` would change ALL VALUES to 0. 

A one liner `Rc <- ifelse(data$Ti >= T_base, 0, 1)` would fix the problem.

In addition, I noticed that in the AT model, the parameter `c` ranges from 0 to 5. It is the same range as Basler et al., 2016, but I think it's incorrect. From my understanding, the logic of the AT model is that chilling would reduce the amount of thermal forcing needed to budburst, so `F_crit` is a negative exponential function of chilling, which means `c` must be negative. Otherwise, more chilling would yield higher `F_crit` in the model. After several tests, I figured `c` should be in the range of `[-0.1, 0]`. Actually, most of the time it should be very close to 0. But, if we want to be secure, maybe making it `[-5, 0]`, only requires more effort for the algorithm to find the suitable value.

Can you check the above issues? Thanks.

**Comment by khufkens** [comment]
Thanks for the report, will look into this later. Feel free to push a pull request with a fix.
